#include <stdio.h>
int main(){
	printf("000000000000000000000000000000");
	printf("\n"); 
	printf("0                            0");
	printf("\n"); 
	printf("0                            0");
	printf("\n"); 	
	printf("0                            0");
	printf("\n"); 	
	printf("0 {Snake Game}               0"); 
	printf("\n"); 	
	printf("0                            0"); 
	printf("\n"); 
	printf("0                            0");
		printf("\n");
	printf("0                            0");
		printf("\n");
	printf("0 Move : arrow button        0"); 	
		printf("\n");
	printf("0                            0");
		printf("\n");
	printf("0 Start : P                  0"); 
		printf("\n");
	printf("0                            0");
		printf("\n");
	printf("0 Go out : ESC               0"); 
		printf("\n");
	printf("0                            0"); 
		printf("\n");
	printf("0                            0");
			printf("\n");
	printf("0                            0"); 
			printf("\n");
	printf("0                            0"); 
		printf("\n");
	printf("0                            0");
		printf("\n");
	printf("0                            0");
	printf("\n");
	printf("0                            0");
	printf("\n");
	printf("000000000000000000000000000000");
}
